Implement module's graphql support
CodeChain-io/foundry pull request #487
Opened 2020-08-25 02:28 UTC by junha1

2020-08-25 08:44 UTC, majecty reviewed
I have some suggestions before reviewing them in detail.

1. How about changing the name of `Machine` to `Config`?
The `machine` is only used to store config values.
2. How about changing the name of `StateMachineFactory` to `GraphQLRoot`?
The name `StateMachineFactory` describes what the type is doing. The value of `StateMachineFactory` is used only in GraphQL query handling. If we use the name `GraphQLRoot`, a future reader can understand how it will be used.

I think the `Factory` name is useful when there is more situation when we want to create the StateMachine with various reason.

I have some questions about the code.

3. How modules provide services with state from a height?
 I understand that we can create StateMachine with state from a height. Getting service of a specific height seems not easy. Maybe each module exposes a service that exports other services from a state(or height)?

2020-08-25 10:02 UTC, junha1 commented
@majecty Let's pause the review of this PR until we have concrete conclusion of the topic (specifying state in services) soon.

2020-08-26 05:03 UTC, majecty requested changes

2020-08-26 05:12 UTC, junha1 commented on timestamp/tests/common/mock_coordinator.rs
>  // along with this program.  If not, see <https://www.gnu.org/licenses/>.
I'll try next time.

2020-08-26 05:13 UTC, majecty approved these changes

2020-08-26 05:14 UTC, merged